name: CompassHunting
version: 1.2
author: InfinityMage
description: Track other players using compasses!
main: club.infinitymage.compasshunting.CompassHunting
api-version: 1.15
commands:
  givecompass:
  track: